vm-count = "4"
vm-host-count = "30"
vm-name = "hpc"
vm-template-name = "CentOSTemplate"
vm-cpu = "2"
vm-ram = "4096"
vm-guest-id = "centos7_64Guest"

vsphere_server = "10.10.10.5"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "Admin@123"
vsphere_datacenter = "Datacenter"
vsphere_cluster = "Cluster01"
datastore = "datastore1"
network_name = "VM Network"
vm-domain = "vsphere.local"
vsphere_host = "10.10.10.3"